### ISSUE TITLE
Users entity

### ISSUE THREAD

**Issue by dmatamoroscr** [duncanjbrown/wp-api-client#5]
Would it be possible to have the gem handle users?
When I attempted to pull users, I got an exception. It seems the WP response for users is different compared to the other types

**Comment by duncanjbrown** [comment]
Would you like to have a go at adding them? Would require a User entity in
lib/wp-api-client/entities. You just need to implement self.represents? to
get started.

**Comment by duncanjbrown** [comment]
New PR #6  should make this easier to try out. I ought to improve the docs on tests/contributing too..

**Comment by dmatamoroscr** [comment]
Sorry, I have been very busy and haven't been able to keep track of everything.
I created a fork and added that entity.
However it is missing tests

https://github.com/avdmatamoros/wp-api-client

**Comment by duncanjbrown** [comment]
Thank you! Let me take a look and I will see if I can roll it in.

**Comment by duncanjbrown** [comment]
Just added
